* Cog_english_labels.do
* Apply English labels to Cognitive assessment variables
* Called from Cog_Read.do - only runs if language == "E"

* Check if language is set to English (using global from master)
if `"$language"' == "E" {

capture program drop apply_cog_english_labels
program define apply_cog_english_labels

* Drop existing labels to avoid conflicts
label drop _all

****************************************
* VALUE LABELS (label define)
****************************************

label define C_0 .a "." 1 "correct" 0 "incorrect"
label define C_1 .a "." 1 "correct" 0 "incorrect"
label define C_2_P_C .a "." 1 "correct" 0 "incorrect"
label define C_2_D .a "." 1 "correct" 0 "incorrect"
label define C_3 .a "." 1 "correct" 0 "incorrect"
label define C_4 .a "." 1 "correct" 0 "incorrect"
label define C_5 .a "." 1 "correct" 0 "incorrect"
label define C_6 .a "." 1 "correct" 0 "incorrect"
label define C_7_D_C .a "." 1 "correct" 0 "incorrect"
label define C_7_P .a "." 1 "correct" 0 "incorrect"
label define C_8 .a "." 1 "correct" 0 "incorrect"
label define C_9 .a "." 1 "correct" 0 "incorrect"
label define C_10 .a "." 1 "correct" 0 "incorrect"
label define C_11 .a "." 1 "correct" 0 "incorrect"
label define C_12 .a "." 1 "correct" 0 "incorrect"
label define C_13 .a "." 1 "correct" 0 "incorrect"
label define C_21 .a "." 1 "correct" 0 "incorrect"
label define C_22 .a "." 1 "correct" 0 "incorrect"
label define C_23 .a "." 1 "correct" 0 "incorrect"
label define C_24 .a "." 1 "correct" 0 "incorrect" 6 "could not (physical limitation)" 7 "refused"
label define C_25 .a "." 1 "correct" 0 "incorrect" 6 "could not (physical limitation)" 7 "refused"
label define C_26 .a "." 1 "correct" 0 "incorrect" 7 "refused"
label define C_27 .a "." 1 "correct" 0 "incorrect" 6 "could not (physical limitation)" 7 "refused"
label define C_28 .a "." 1 "correct" 0 "incorrect" 6 "could not (physical limitation)" 7 "refused"
label define C_29 .a "." 1 "correct" 0 "incorrect" 6 "could not (physical limitation)" 7 "refused"
label define C_30 .a "." 1 "correct" 0 "incorrect" 5 "could not (illiterate)" 6 "could not (physical limitation)" 7 "refused"
label define C_31 .a "." 0 "0" 1 "1" 5 "could not (illiterate)" 6 "could not (physical limitation)" 7 "refused"
label define C_32 .a "." 1 "yes" 6 "could not (physical limitation)" 7 "refused"
label define G_1 .a "." 1 "yes" 2 "no"
label define C_40 .a "." 0 "no" 1 "yes" 777 "refused"
label define C_43 .a "." 0 "no" 1 "yes" 666 "could not (physical limitation)" 777 "refused"
label define C_45 .a "." 1 "correct" 0 "incorrect" 2 "wants to start over" 7 "refused"
label define C_46 .a "." 1 "correct" 0 "incorrect" 7 "refused"
label define C_48 .a "." 1 "correct" 0 "incorrect" 6 "could not (physical limitation)" 7 "refused"
label define C_49 .a "." 1 "correct" 0 "incorrect" 6 "could not (physical limitation)" 7 "refused"
label define C_50 .a "." 1 "correct" 0 "incorrect" 6 "could not (physical limitation)" 7 "refused"
label define C_51 .a "." 1 "correct" 0 "incorrect" 6 "could not (physical limitation)" 7 "refused"
label define C_52 .a "." 1 "correct" 0 "incorrect" 6 "could not (physical limitation)" 7 "refused"
label define C_53 .a "." 1 "correct" 0 "incorrect" 7 "refused"
label define C_54 .a "." 1 "correct" 0 "incorrect" 7 "refused"
label define C_55 .a "." 1 "correct" 0 "incorrect" 7 "refused"
label define C_56 .a "." 1 "correct" 0 "incorrect" 7 "refused"
label define C_58 .a "." 1 "answered" 2 "did not answer"
label define C_59 .a "." 1 "answered" 2 "did not answer"
label define C_60 .a "." 1 "answered" 2 "did not answer"
label define C_61 .a "." 1 "correct" 0 "incorrect" 6 "could not (physical limitation)" 7 "refused"
label define C_62 .a "." 1 "correct" 0 "incorrect" 6 "could not (physical limitation)" 7 "refused"
label define C_65 .a "." 1 "correct" 0 "incorrect"
label define G_2 .a "." 1 "yes" 2 "no"
label define C_66A .a "." 0 "yes, exactly" 1 "yes, approximately" 2 "forgot the element"
label define C_66B .a "." 0 "yes, exactly" 1 "yes, approximately" 2 "forgot the element"
label define C_66C .a "." 0 "yes, exactly" 1 "yes, approximately" 2 "forgot the element"
label define C_66D .a "." 0 "yes, exactly" 1 "yes, approximately" 2 "forgot the element"
label define C_66E .a "." 0 "yes, exactly" 1 "yes, approximately" 2 "forgot the element"
label define C_66F .a "." 0 "yes, exactly" 1 "yes, approximately" 2 "forgot the element"
label define C_67_01 .a "." 0 "yes, exactly" 1 "yes, approximately" 2 "forgot the element"
label define C_67_02 .a "." 0 "yes, exactly" 1 "yes, approximately" 2 "forgot the element"
label define C_67_03 .a "." 0 "yes, exactly" 1 "yes, approximately" 2 "forgot the element"
label define C_67_04 .a "." 0 "yes, exactly" 1 "yes, approximately" 2 "forgot the element"
label define C_67_05 .a "." 0 "yes, exactly" 1 "yes, approximately" 2 "forgot the element"
label define C_67_06 .a "." 0 "yes, exactly" 1 "yes, approximately" 2 "forgot the element"
label define C_67_07 .a "." 0 "yes, exactly" 1 "yes, approximately" 2 "forgot the element"
label define C_67_08 .a "." 0 "yes, exactly" 1 "yes, approximately" 2 "forgot the element"
label define C_67_09 .a "." 0 "yes, exactly" 1 "yes, approximately" 2 "forgot the element"
label define C_67_10 .a "." 0 "yes, exactly" 1 "yes, approximately" 2 "forgot the element"
label define C_67_11 .a "." 0 "yes, exactly" 1 "yes, approximately" 2 "forgot the element"
label define C_67_12 .a "." 0 "yes, exactly" 1 "yes, approximately" 2 "forgot the element"
label define C_67_13_C .a "." 0 "yes, exactly" 1 "yes, approximately" 2 "forgot the element"
label define C_67_13_D .a "." 0 "yes, exactly" 1 "yes, approximately" 2 "forgot the element"
label define C_67_13_P .a "." 0 "yes, exactly" 1 "yes, approximately" 2 "forgot the element"
label define C_67_14 .a "." 0 "yes, exactly" 1 "yes, approximately" 2 "forgot the element"
label define C_67_15 .a "." 0 "yes, exactly" 1 "yes, approximately" 2 "forgot the element"
label define C_67_16 .a "." 0 "yes, exactly" 1 "yes, approximately" 2 "forgot the element"
label define C_67_17 .a "." 0 "yes, exactly" 1 "yes, approximately" 2 "forgot the element"
label define C_67_18 .a "." 0 "yes, exactly" 1 "yes, approximately" 2 "forgot the element"
label define C_67_19 .a "." 0 "yes, exactly" 1 "yes, approximately" 2 "forgot the element"
label define C_67_20 .a "." 0 "yes, exactly" 1 "yes, approximately" 2 "forgot the element"
label define C_67_21 .a "." 0 "yes, exactly" 1 "yes, approximately" 2 "forgot the element"
label define C_67_22 .a "." 0 "yes, exactly" 1 "yes, approximately" 2 "forgot the element"
label define C_67_23 .a "." 0 "yes, exactly" 1 "yes, approximately" 2 "forgot the element"
label define C_67_24 .a "." 0 "yes, exactly" 1 "yes, approximately" 2 "forgot the element"
label define C_67_25 .a "." 0 "yes, exactly" 1 "yes, approximately" 2 "forgot the element"
label define C_68_01 .a "." 1 "yes" 2 "no"
label define C_68_02 .a "." 1 "yes" 2 "no"
label define C_68_03 .a "." 1 "yes" 2 "no"
label define C_68_04 .a "." 1 "yes" 2 "no"
label define C_68_05 .a "." 1 "yes" 2 "no"
label define C_68_06 .a "." 1 "yes" 2 "no"
label define C_68_07 .a "." 1 "yes" 2 "no"
label define C_68_08 .a "." 1 "yes" 2 "no"
label define C_68_09 .a "." 1 "yes" 2 "no"
label define C_68_10 .a "." 1 "yes" 2 "no"
label define C_68_11 .a "." 1 "yes" 2 "no"
label define C_68_12 .a "." 1 "yes" 2 "no"
label define C_68_13 .a "." 1 "yes" 2 "no"
label define C_68_14 .a "." 1 "yes" 2 "no"
label define C_68_15 .a "." 1 "yes" 2 "no"
label define C_68_16 .a "." 1 "yes" 2 "no"
label define C_68_17 .a "." 1 "yes" 2 "no"
label define C_68_18 .a "." 1 "yes" 2 "no"
label define C_68_19 .a "." 1 "yes" 2 "no"
label define C_68_20 .a "." 1 "yes" 2 "no"
label define C_69_C .a "." 1 "correct" 0 "incorrect"
label define C_69_D .a "." 1 "correct" 0 "incorrect"
label define C_69_P .a "." 1 "correct" 0 "incorrect"
label define C_70_D_C .a "." 1 "correct" 0 "incorrect"
label define C_70_P .a "." 1 "correct" 0 "incorrect"
label define C_71_C .a "." 1 "correct" 0 "incorrect"
label define C_71_P .a "." 1 "correct" 0 "incorrect"
label define C_71_D .a "." 1 "correct" 0 "incorrect"
label define C_72_1 .a "." 1 "yes" 6 "could not (physical limitation)" 7 "refused"
label define C_72_2 .a "." 1 "yes" 6 "could not (physical limitation)" 7 "refused"
label define C_72_3 .a "." 1 "yes" 6 "could not (physical limitation)" 7 "refused"
label define C_72_4 .a "." 1 "yes" 6 "could not (physical limitation)" 7 "refused"
label define C_77A .a "." 0 "yes, exactly" 1 "yes, approximately" 2 "forgot the element"
label define C_77B .a "." 0 "yes, exactly" 1 "yes, approximately" 2 "forgot the element"
label define C_77C .a "." 0 "yes, exactly" 1 "yes, approximately" 2 "forgot the element"
label define C_77D .a "." 0 "yes, exactly" 1 "yes, approximately" 2 "forgot the element"
label define C_77E .a "." 0 "yes, exactly" 1 "yes, approximately" 2 "forgot the element"
label define C_77F .a "." 0 "yes, exactly" 1 "yes, approximately" 2 "forgot the element"
label define C_78_01 .a "." 0 "yes, exactly" 1 "yes, approximately" 2 "forgot the element"
label define C_78_02 .a "." 0 "yes, exactly" 1 "yes, approximately" 2 "forgot the element"
label define C_78_03 .a "." 0 "yes, exactly" 1 "yes, approximately" 2 "forgot the element"
label define C_78_04 .a "." 0 "yes, exactly" 1 "yes, approximately" 2 "forgot the element"
label define C_78_05 .a "." 0 "yes, exactly" 1 "yes, approximately" 2 "forgot the element"
label define C_78_06 .a "." 0 "yes, exactly" 1 "yes, approximately" 2 "forgot the element"
label define C_78_07 .a "." 0 "yes, exactly" 1 "yes, approximately" 2 "forgot the element"
label define C_78_08 .a "." 0 "yes, exactly" 1 "yes, approximately" 2 "forgot the element"
label define C_78_09 .a "." 0 "yes, exactly" 1 "yes, approximately" 2 "forgot the element"
label define C_78_10 .a "." 0 "yes, exactly" 1 "yes, approximately" 2 "forgot the element"
label define C_78_11 .a "." 0 "yes, exactly" 1 "yes, approximately" 2 "forgot the element"
label define C_78_12 .a "." 0 "yes, exactly" 1 "yes, approximately" 2 "forgot the element"
label define C_78_13 .a "." 0 "yes, exactly" 1 "yes, approximately" 2 "forgot the element"
label define C_78_14 .a "." 0 "yes, exactly" 1 "yes, approximately" 2 "forgot the element"
label define C_78_15 .a "." 0 "yes, exactly" 1 "yes, approximately" 2 "forgot the element"
label define C_78_16 .a "." 0 "yes, exactly" 1 "yes, approximately" 2 "forgot the element"
label define C_78_17 .a "." 0 "yes, exactly" 1 "yes, approximately" 2 "forgot the element"
label define C_78_18 .a "." 0 "yes, exactly" 1 "yes, approximately" 2 "forgot the element"
label define C_78_19 .a "." 0 "yes, exactly" 1 "yes, approximately" 2 "forgot the element"
label define C_78_20 .a "." 0 "yes, exactly" 1 "yes, approximately" 2 "forgot the element"
label define C_78_21 .a "." 0 "yes, exactly" 1 "yes, approximately" 2 "forgot the element"
label define C_78_22 .a "." 0 "yes, exactly" 1 "yes, approximately" 2 "forgot the element"
label define C_78_23 .a "." 0 "yes, exactly" 1 "yes, approximately" 2 "forgot the element"
label define C_78_24 .a "." 0 "yes, exactly" 1 "yes, approximately" 2 "forgot the element"
label define C_78_25 .a "." 0 "yes, exactly" 1 "yes, approximately" 2 "forgot the element"
label define C_79_1 .a "." 1 "yes" 6 "could not (physical limitation)" 4 "could not remember the figure" 7 "refused"
label define C_79_2 .a "." 1 "yes" 6 "could not (physical limitation)" 4 "could not remember the figure" 7 "refused"
label define C_79_3 .a "." 1 "yes" 6 "could not (physical limitation)" 4 "could not remember the figure" 7 "refused"
label define C_79_4 .a "." 1 "yes" 6 "could not (physical limitation)" 4 "could not remember the figure" 7 "refused"
label define C_80A .a "." 2 "no" 1 "yes"
label define C_80B .a "." 2 "no" 1 "yes"
label define C_80C .a "." 2 "no" 1 "yes"
label define C_81 .a "." 1 "excellent" 2 "very good" 3 "good" 4 "regular" 5 "poor" 6 "blind"
label define C_82 .a "." 1 "excellent" 2 "very good" 3 "good" 4 "regular" 5 "poor" 6 "deaf"

* Checkbox labels for word recall items
label define C_33_A 0 "false" 7 "true"
label define C_33_1 0 "false" 1 "true"
label define C_33_2 0 "false" 1 "true"
label define C_33_3 0 "false" 1 "true"
label define C_33_4 0 "false" 1 "true"
label define C_33_5 0 "false" 1 "true"
label define C_33_6 0 "false" 1 "true"
label define C_33_7 0 "false" 1 "true"
label define C_33_8 0 "false" 1 "true"
label define C_33_9 0 "false" 1 "true"
label define C_33_10 0 "false" 1 "true"
label define C_34_A 0 "false" 7 "true"
label define C_34_1 0 "false" 1 "true"
label define C_34_2 0 "false" 1 "true"
label define C_34_3 0 "false" 1 "true"
label define C_34_4 0 "false" 1 "true"
label define C_34_5 0 "false" 1 "true"
label define C_34_6 0 "false" 1 "true"
label define C_34_7 0 "false" 1 "true"
label define C_34_8 0 "false" 1 "true"
label define C_34_9 0 "false" 1 "true"
label define C_34_10 0 "false" 1 "true"
label define C_35_A 0 "false" 7 "true"
label define C_35_1 0 "false" 1 "true"
label define C_35_2 0 "false" 1 "true"
label define C_35_3 0 "false" 1 "true"
label define C_35_4 0 "false" 1 "true"
label define C_35_5 0 "false" 1 "true"
label define C_35_6 0 "false" 1 "true"
label define C_35_7 0 "false" 1 "true"
label define C_35_8 0 "false" 1 "true"
label define C_35_9 0 "false" 1 "true"
label define C_35_10 0 "false" 1 "true"
label define C_63_A 0 "false" 7 "true"
label define C_63_1 0 "false" 1 "true"
label define C_63_2 0 "false" 1 "true"
label define C_63_3 0 "false" 1 "true"
label define C_63_4 0 "false" 1 "true"
label define C_63_5 0 "false" 1 "true"
label define C_63_6 0 "false" 1 "true"
label define C_63_7 0 "false" 1 "true"
label define C_63_8 0 "false" 1 "true"
label define C_63_9 0 "false" 1 "true"
label define C_63_10 0 "false" 1 "true"
label define C_66_A 0 "false" 7 "true"
label define C_67_A 0 "false" 7 "true"
label define C_68_A 0 "false" 7 "true"
label define C_77_A 0 "false" 7 "true"
label define C_78_A 0 "false" 7 "true"

label define checkbox_label 0 "unchecked" 1 "checked", replace

****************************************
* VARIABLE LABELS (label variable)
****************************************

capture label variable c_interid "INTERVIEWER NUMBER"
capture label variable c_houseid "HOUSE NUMBER"
capture label variable c_clustid "CLUSTER NUMBER:"
capture label variable c_particid "PARTICIPANT NUMBER"
capture label variable c_country "Country"
capture label variable c_houseid2 "HOUSE NUMBER"
capture label variable c_conglid2 "CLUSTER NUMBER:"
capture label variable c_particid2 "PARTICIPANT NUMBER"
capture label variable c_deviceid1 "Device ID:"
capture label variable c_0 "0. I want you to remember my name. My name is xxxxxxx. Can you repeat it please?"
capture label variable c_1 "1. What year is it?"
capture label variable c_2_p_c "2. What season is it?"
capture label variable c_2_d "2. What season is it?"
capture label variable c_3 "3. What month is it?"
capture label variable c_4 "4. What date of the month is it? (±1 day)"
capture label variable c_5 "5. What day of the week is today?"
capture label variable c_6 "6. What country are we in?"
capture label variable c_7_d_c "7. What province are we in?"
capture label variable c_7_p "7. What municipality (or city/town) are we in?"
capture label variable c_8 "8. What city/town/neighborhood/housing development are we in?"
capture label variable c_9 "9. What building/place are we in?"
capture label variable c_10 "10. What room are we in?"
capture label variable c_11 "11. PR/DR: Apple / CU: Boat"
capture label variable c_12 "12. PR/DR: Peso / CU: House"
capture label variable c_13 "13. PR/DR: Table / CU: Fish"
capture label variable c_14 "14. Number of attempts."
capture label variable c_15 "15. How much is 100 minus 7?"
capture label variable c_16 "16. Subtraction #2"
capture label variable c_17 "17. Subtraction #3"
capture label variable c_18 "18. Subtraction #4"
capture label variable c_19 "19. Subtraction #5"
capture label variable c_20 "20. Write the letters in the order said by the interviewee."
capture label variable c_21 "21. PR/DR: Apple / CU: Boat"
capture label variable c_22 "22. PR/DR: Peso / CU: House"
capture label variable c_23 "23. PR/DR: Table / CU: Fish"
capture label variable c_24 "24. What is this? (Show a pencil or pen.)"
capture label variable c_25 "25. What is this? (Show a watch.)"
capture label variable c_26 "26. Did they repeat correctly?"
capture label variable c_26_1 "26.1 Number of attempts"
capture label variable c_27 "27. Took the paper with the right hand?"
capture label variable c_28 "28. Folded the paper in half?"
capture label variable c_29 "29. Placed the paper on the floor [or table/legs]"
capture label variable c_30 "30. CLOSE YOUR EYES"
capture label variable c_31 "31. Please write a sentence."
capture label variable c_32 "32. Did they try to draw the figure?"
capture label variable pent_pic "TAKE A PHOTO OF THE PENTAGON DRAWING"
capture label variable c_33_a "Refused to answer?"
capture label variable c_33_1 "Butter"
capture label variable c_33_2 "Arm"
capture label variable c_33_3 "Letter"
capture label variable c_33_4 "Queen"
capture label variable c_33_5 "Ticket"
capture label variable c_33_6 "Grass"
capture label variable c_33_7 "Corner"
capture label variable c_33_8 "Rock"
capture label variable c_33_9 "Book"
capture label variable c_33_10 "Stick"
capture label variable c_34_a "Refused to answer?"
capture label variable c_34_1 "Butter"
capture label variable c_34_2 "Arm"
capture label variable c_34_3 "Letter"
capture label variable c_34_4 "Queen"
capture label variable c_34_5 "Ticket"
capture label variable c_34_6 "Grass"
capture label variable c_34_7 "Corner"
capture label variable c_34_8 "Rock"
capture label variable c_34_9 "Book"
capture label variable c_34_10 "Stick"
capture label variable c_35_a "Refused to answer?"
capture label variable c_35_1 "Butter"
capture label variable c_35_2 "Arm"
capture label variable c_35_3 "Letter"
capture label variable c_35_4 "Queen"
capture label variable c_35_5 "Ticket"
capture label variable c_35_6 "Grass"
capture label variable c_35_7 "Corner"
capture label variable c_35_8 "Rock"
capture label variable c_35_9 "Book"
capture label variable c_35_10 "Stick"
capture label variable g_1 "G.1 Is it okay if we record this activity?"
capture label variable g_1_file "START AUDIO RECORDING NOW"
capture label variable c_40 "40. Did they try this verbal fluency task?"
capture label variable anim_pic "TAKE A PHOTO OF THE ANIMAL DRAWING SHEET NOW"
capture label variable c_43 "43. Did they try this verbal fluency task?"
capture label variable symb_pic "TAKE A PHOTO OF THE SYMBOL SHEET NOW"
capture label variable c_45 "45. Count backward from 20 to 11 (or 19 to 10)"
capture label variable c_45_a "45A. Time score (60 if incorrect)"
capture label variable c_46 "46. SECOND ATTEMPT (only if want to start over)"
capture label variable c_46_a "46A. TIME (SCORE 60 IF THE COUNT IS INCORRECT)"
capture label variable c_48 "48. What is this called? (chair)"
capture label variable c_49 "49. What is this called? (shoes)"
capture label variable c_50 "50. What is this called? (knuckles)"
capture label variable c_51 "51. What is this called? (elbows)"
capture label variable c_52 "52. What is this called? (shoulders)"
capture label variable c_53 "53. What is a bridge?"
capture label variable c_54 "54. What can you do with a hammer?"
capture label variable c_55 "55. What do people do in a church or temple?"
capture label variable c_56 "56. Where do we go to buy medicines?"
capture label variable c_58 "58. What are the names of the two most important streets near your house?"
capture label variable c_59 "59. Where is the nearest store/bodega/grocery store?"
capture label variable c_60 "60. What is your address?"
capture label variable c_61 "61. Please nod your head, as if to say yes."
capture label variable c_62 "62. Please point first at the window and then at the door."
capture label variable c_63_a "Refused to answer?"
capture label variable c_63_1 "Butter"
capture label variable c_63_2 "Arm"
capture label variable c_63_3 "Letter"
capture label variable c_63_4 "Queen"
capture label variable c_63_5 "Ticket"
capture label variable c_63_6 "Grass"
capture label variable c_63_7 "Corner"
capture label variable c_63_8 "Rock"
capture label variable c_63_9 "Book"
capture label variable c_63_10 "Stick"
capture label variable c_65 "65. Do you remember my name? What is it?"
capture label variable g_2 "G.2. Is it okay if we record this activity?"
capture label variable c_66_a "Refused to answer?"
capture label variable g_2_file "START AUDIO RECORDING NOW"
capture label variable c_66a "66.A. Three children"
capture label variable c_66b "66.B. House caught fire"
capture label variable c_66c "66.C. Brave man managed to climb"
capture label variable c_66d "66.D. Pull the children out"
capture label variable c_66e "66.E. Small cuts"
capture label variable c_66f "66.F. Everyone is fine"
capture label variable c_67_a "Refused to answer?"
capture label variable g_2_file2 "START AUDIO RECORDING NOW"
capture label variable c_67_01 "67.1 Maria"
capture label variable c_67_02 "67.2. Moreno"
capture label variable c_67_03 "67.3. from Northern"
capture label variable c_67_04 "67.4. Santo Domingo(DR)/ Habana(Cuba)/ San Juan (PR)"
capture label variable c_67_05 "67.5. Worked"
capture label variable c_67_06 "67.6. Cook"
capture label variable c_67_07 "67.7. Cafeteria"
capture label variable c_67_08 "67.8. Corner"
capture label variable c_67_09 "67.9. Reported"
capture label variable c_67_10 "67.10. to the station"
capture label variable c_67_11 "67.11. Police"
capture label variable c_67_12 "67.12. Had been robbed"
capture label variable c_67_13_c "67.13. in avenida Paseo"
capture label variable c_67_13_d "67.13. in calle Duarte"
capture label variable c_67_13_p "67.13. in avenida La Palma"
capture label variable c_67_14 "67.14. The night before"
capture label variable c_67_15 "67.15. And were stolen"
capture label variable c_67_16 "67.16. 520 pesos"
capture label variable c_67_17 "67.17. has 4"
capture label variable c_67_18 "67.18. Young children"
capture label variable c_67_19 "67.19. The rent is due"
capture label variable c_67_20 "67.20. Haven't eaten"
capture label variable c_67_21 "67.21. In two days"
capture label variable c_67_22 "67.22. The police"
capture label variable c_67_23 "67.23. Moved by the woman's story"
capture label variable c_67_24 "67.24. Organized a collection of money"
capture label variable c_67_25 "67.25. For her"
capture label variable c_68_a "Refused to answer?"
capture label variable c_68_01 "68.1. Plaza"
capture label variable c_68_02 "68.2. Coffee"
capture label variable c_68_03 "68.3. Butter"
capture label variable c_68_04 "68.4. Peso"
capture label variable c_68_05 "68.5. Arm"
capture label variable c_68_06 "68.6. Book"
capture label variable c_68_07 "68.7. Five"
capture label variable c_68_08 "68.8. Card"
capture label variable c_68_09 "68.9. Hotel"
capture label variable c_68_10 "68.10. Mountain"
capture label variable c_68_11 "68.11. Queen"
capture label variable c_68_12 "68.12. Corner"
capture label variable c_68_13 "68.13. Slipper"
capture label variable c_68_14 "68.14. Stick"
capture label variable c_68_15 "68.15. Villa"
capture label variable c_68_16 "68.16. Rope"
capture label variable c_68_17 "68.17. Ticket"
capture label variable c_68_18 "68.18. Troops"
capture label variable c_68_19 "68.19. Grass"
capture label variable c_68_20 "68.20. Rock"
capture label variable c_69_c "69. Name of Apostle of Cuba who died in Dos Rios in 1895?"
capture label variable c_69_d "69. Name of fathers of homeland who proclaimed independence in 1844?"
capture label variable c_69_p "69. Who discovered Puerto Rico for the Europeans?"
capture label variable c_70_d_c "70. What is the name of the president?"
capture label variable c_70_p "70. What is the name of the governor?"
capture label variable c_71_c "71. Name of president who succeeded Fidel Castro?"
capture label variable c_71_p "71. What is the name of the resident commissioner?"
capture label variable c_71_d "71. What is the name of the vice-president?"
capture label variable c_72_1 "72.1 Did they try to draw the circle?"
capture label variable c_72_2 "72.2. Did they try to draw the diamond?"
capture label variable c_72_3 "72.3. Did they try to draw the two crossed rectangles?"
capture label variable c_72_4 "72.4. Did they try to draw the cube?"
capture label variable c_72_1_pic "TAKE A PHOTO OF THE CIRCLE DRAWING"
capture label variable c_72_2_pic "TAKE A PHOTO OF THE DIAMOND DRAWING"
capture label variable c_72_3_pic "TAKE A PHOTO OF THE DRAWING OF CROSSED RECTANGLES"
capture label variable c_72_4_pic "TAKE A PHOTO OF THE CUBE DRAWING"
capture label variable c_77_a "Refused to answer?"
capture label variable g_3_file "START AUDIO RECORDING NOW"
capture label variable c_77a "77.A. Three children"
capture label variable c_77b "77.B. House caught fire"
capture label variable c_77c "77.C. Brave man managed to climb"
capture label variable c_77d "77.D. pull the children out"
capture label variable c_77e "77.E. small cuts"
capture label variable c_77f "77.F. Everyone is fine"
capture label variable c_78_a "Refused to answer?"
capture label variable g_3_file2 "START AUDIO RECORDING NOW"
capture label variable c_78_01 "78.1 Maria"
capture label variable c_78_02 "78.2. Moreno"
capture label variable c_78_03 "78.3. from Northern"
capture label variable c_78_04 "78.4. Santo Domingo(DR)/ Habana(Cuba)/ San Juan (PR)"
capture label variable c_78_05 "78.5. Worked"
capture label variable c_78_06 "78.6. Cook"
capture label variable c_78_07 "78.7. Cafeteria"
capture label variable c_78_08 "78.8. Corner"
capture label variable c_78_09 "78.9. Reported"
capture label variable c_78_10 "78.10. to the station"
capture label variable c_78_11 "78.11. Police"
capture label variable c_78_12 "78.12. Had been robbed"
capture label variable c_78_13 "78.13. in calle Duarte (DR) / avenida Paseo (Cuba) / avenida La Palma (PR)"
capture label variable c_78_14 "78.14. The night before"
capture label variable c_78_15 "78.15. And were stolen"
capture label variable c_78_16 "78.16. 520 pesos"
capture label variable c_78_17 "78.17. has 4"
capture label variable c_78_18 "78.18. Young children"
capture label variable c_78_19 "78.19. The rent is due"
capture label variable c_78_20 "78.20. Haven't eaten"
capture label variable c_78_21 "78.21. In two days"
capture label variable c_78_22 "78.22. The police"
capture label variable c_78_23 "78.23. Moved by the woman's story"
capture label variable c_78_24 "78.24. Organized a collection of money"
capture label variable c_78_25 "78.25. For her"
capture label variable c_79_1 "79.1 Did they try to draw the circle?"
capture label variable c_79_2 "79.2. Did they try to draw the diamond?"
capture label variable c_79_3 "79.3. Did they try to draw the two crossed rectangles?"
capture label variable c_79_4 "79.4. Did they try to draw the cube?"
capture label variable c_79_1_pic "TAKE A PHOTO OF THE CIRCLE DRAWING"
capture label variable c_79_2_pic "TAKE A PHOTO OF THE DIAMOND DRAWING"
capture label variable c_79_3_pic "TAKE A PHOTO OF THE DRAWING OF CROSSED RECTANGLES"
capture label variable c_79_4_pic "TAKE A PHOTO OF THE CUBE DRAWING"
capture label variable c_80a "80a. Did the participant have difficulty due to their vision?"
capture label variable c_80b "80b. Did the participant have difficulty due to their hearing?"
capture label variable c_80c "80c. Did the participant have difficulty due to their physical disability?"
capture label variable c_81 "81. How is the participant's vision (with glasses, if they normally wear them)?"
capture label variable c_82 "82. How is the participant's ear/hearing range (with device if normally used)?"
capture label variable c_deviceid2 "Device ID:"

****************************************
* APPLY VALUE LABELS TO VARIABLES (label values)
****************************************

capture label values c_33_a checkbox_label
capture label values c_33_1 checkbox_label
capture label values c_33_2 checkbox_label
capture label values c_33_3 checkbox_label
capture label values c_33_4 checkbox_label
capture label values c_33_5 checkbox_label
capture label values c_33_6 checkbox_label
capture label values c_33_7 checkbox_label
capture label values c_33_8 checkbox_label
capture label values c_33_9 checkbox_label
capture label values c_33_10 checkbox_label
capture label values c_34_a checkbox_label
capture label values c_34_1 checkbox_label
capture label values c_34_2 checkbox_label
capture label values c_34_3 checkbox_label
capture label values c_34_4 checkbox_label
capture label values c_34_5 checkbox_label
capture label values c_34_6 checkbox_label
capture label values c_34_7 checkbox_label
capture label values c_34_8 checkbox_label
capture label values c_34_9 checkbox_label
capture label values c_34_10 checkbox_label
capture label values c_35_a checkbox_label
capture label values c_35_1 checkbox_label
capture label values c_35_2 checkbox_label
capture label values c_35_3 checkbox_label
capture label values c_35_4 checkbox_label
capture label values c_35_5 checkbox_label
capture label values c_35_6 checkbox_label
capture label values c_35_7 checkbox_label
capture label values c_35_8 checkbox_label
capture label values c_35_9 checkbox_label
capture label values c_35_10 checkbox_label
capture label values c_63_a checkbox_label
capture label values c_63_1 checkbox_label
capture label values c_63_2 checkbox_label
capture label values c_63_3 checkbox_label
capture label values c_63_4 checkbox_label
capture label values c_63_5 checkbox_label
capture label values c_63_6 checkbox_label
capture label values c_63_7 checkbox_label
capture label values c_63_8 checkbox_label
capture label values c_63_9 checkbox_label
capture label values c_63_10 checkbox_label
capture label values c_66_a checkbox_label
capture label values c_67_a checkbox_label
capture label values c_68_a checkbox_label
capture label values c_77_a checkbox_label
capture label values c_78_a checkbox_label

end

* Call the program
apply_cog_english_labels

} // end if language == "E"
