********************************************************************************
* STEP 7: VALIDATE CADAS VS 1066 BASELINE
* Compare variable distributions between CADAS output and original 1066 data
* Exports comparison to CSV for detecting anomalies
* Creates both overall and country-specific comparisons
********************************************************************************

display _newline(1)
display "--------------------------------------------------------------------------------"
display "STEP 7: Validating CADAS vs 1066 Baseline..."
display "--------------------------------------------------------------------------------"

*-------------------------------------------------------------------------------
* CONFIGURATION
*-------------------------------------------------------------------------------

* Path to 1066 reference dataset (generated by generating_coeffs_from_1066.do)
local baseline_path "/Users/chrissoria/Documents/Research/CADAS_1066/1066/1066_reference_for_validation.dta"

* Path to original 1066 baseline data (has countryid for country-specific comparison)
local baseline_raw_path "/Users/chrissoria/Documents/Research/CADAS_1066/1066/data/1066_Baseline_data.dta"

* Mapping from CADAS country codes to 1066 countryid
* CADAS: 0=Puerto Rico, 1=Dominican Republic, 2=Cuba
* 1066:  1=Cuba (n=2813), 2=DR (n=2011), 20=Puerto Rico (n=2009)
if $country == 0 {
    local baseline_countryid = 20     // Puerto Rico -> 1066 countryid 20
    local country_name "Puerto Rico"
}
else if $country == 1 {
    local baseline_countryid = 2      // Dominican Republic -> 1066 countryid 2
    local country_name "Dominican Republic"
}
else if $country == 2 {
    local baseline_countryid = 1      // Cuba -> 1066 countryid 1
    local country_name "Cuba"
}

display "CADAS Country: `country_name' (code $country)"
display "1066 Baseline countryid: `baseline_countryid'"

* Variables to compare
local all_vars "pencil watch chair shoes knuckle elbow should bridge hammer pray chemist repeat town chief street store address longmem month day year season nod point circle pentag pentag_strict nametot count animals wordimm worddel paper story cogscore immed learn1 learn2 learn3 recall activ mental memory put kept frdname famname convers wordfind wordwrg past lastsee lastday orient lostout lostin chores hobby money change reason feed dress toilet miss1 miss3 misstot relscore dem1066_score dem1066"

*-------------------------------------------------------------------------------
* CALCULATE CADAS STATISTICS
*-------------------------------------------------------------------------------

display "Calculating CADAS statistics..."

* Load CADAS 1066 output
use 1066.dta, clear
local cadas_n = _N

* Set up postfile for CADAS stats
tempfile cadas_stats
postfile cadas_handle str32 variable double(cadas_n cadas_mean cadas_sd cadas_min cadas_max) using `cadas_stats', replace

* Calculate stats for each variable
foreach var of local all_vars {
    capture confirm variable `var'
    if _rc == 0 {
        quietly summarize `var'
        post cadas_handle ("`var'") (r(N)) (r(mean)) (r(sd)) (r(min)) (r(max))
    }
    else {
        display "  Warning: `var' not found in CADAS data"
        post cadas_handle ("`var'") (.) (.) (.) (.) (.)
    }
}

postclose cadas_handle
display "  CADAS statistics calculated"

*-------------------------------------------------------------------------------
* CALCULATE 1066 BASELINE STATISTICS
*-------------------------------------------------------------------------------

display "Calculating 1066 Baseline statistics..."

* Set up postfile for baseline stats
tempfile baseline_stats
postfile baseline_handle str32 variable double(baseline_n baseline_mean baseline_sd baseline_min baseline_max) using `baseline_stats', replace

* Load 1066 baseline data
capture use "`baseline_path'", clear
if _rc != 0 {
    display as error "ERROR: Could not load 1066 baseline data from:"
    display as error "  `baseline_path'"
    display as error "Creating empty baseline stats."

    * Post empty values for all variables
    foreach var of local all_vars {
        post baseline_handle ("`var'") (.) (.) (.) (.) (.)
    }
}
else {
    * Calculate stats for each variable
    foreach var of local all_vars {
        capture confirm variable `var'
        if _rc == 0 {
            quietly summarize `var'
            post baseline_handle ("`var'") (r(N)) (r(mean)) (r(sd)) (r(min)) (r(max))
        }
        else {
            display "  Note: `var' not found in 1066 baseline"
            post baseline_handle ("`var'") (.) (.) (.) (.) (.)
        }
    }
    display "  Baseline statistics calculated"
}

postclose baseline_handle

*-------------------------------------------------------------------------------
* MERGE AND CALCULATE DIFFERENCES
*-------------------------------------------------------------------------------

display "Merging datasets and calculating differences..."

use `cadas_stats', clear
merge 1:1 variable using `baseline_stats', nogenerate

* Calculate difference metrics
gen double mean_diff = cadas_mean - baseline_mean
gen double mean_pct_diff = ((cadas_mean - baseline_mean) / baseline_mean) * 100 if baseline_mean != 0 & !missing(baseline_mean)
gen double min_diff = cadas_min - baseline_min
gen double max_diff = cadas_max - baseline_max

* Flag large differences (>10% or >0.5 absolute for small values)
gen byte flag_mean = 0
replace flag_mean = 1 if abs(mean_pct_diff) > 10 & !missing(mean_pct_diff)
replace flag_mean = 1 if abs(mean_diff) > 0.5 & missing(mean_pct_diff) & !missing(mean_diff)

* Sort by absolute pct diff, largest first (before converting to string)
gen abs_pct_diff = abs(mean_pct_diff)
gsort -abs_pct_diff variable
drop abs_pct_diff

* Convert to string with formatting for clean CSV export
foreach var in cadas_mean cadas_sd cadas_min cadas_max baseline_mean baseline_sd baseline_min baseline_max mean_diff {
    tostring `var', replace format(%9.2f) force
}
tostring mean_pct_diff, replace format(%9.0f) force

* Order variables nicely
order variable cadas_n cadas_mean cadas_sd cadas_min cadas_max ///
      baseline_n baseline_mean baseline_sd baseline_min baseline_max ///
      mean_diff mean_pct_diff flag_mean

*-------------------------------------------------------------------------------
* DISPLAY SUMMARY
*-------------------------------------------------------------------------------

display _newline(1)
display "================================================================================"
display "VALIDATION SUMMARY"
display "================================================================================"

* Count flagged variables
quietly count if flag_mean == 1
local n_flagged = r(N)

if `n_flagged' > 0 {
    display as result "Variables with large mean differences (>10% or >0.5):"
    list variable cadas_mean baseline_mean mean_diff mean_pct_diff if flag_mean == 1, noobs
}
else {
    display as result "No variables with large mean differences detected."
}

display _newline(1)
display "Full comparison table:"
list variable cadas_mean baseline_mean mean_diff mean_pct_diff cadas_min cadas_max baseline_min baseline_max, noobs

*-------------------------------------------------------------------------------
* EXPORT TO CSV
*-------------------------------------------------------------------------------

display _newline(1)
capture mkdir "$data_path/1066_diagnostics"
export delimited using "$data_path/1066_diagnostics/validation_cadas_vs_1066.csv", replace

* Also copy to Google Drive
local gdrive_path "/Users/chrissoria/Google Drive/other computers/My Laptop (1)/documents/cadas/data/CADAS data upload/cuba/latest_data/1066_DIAGNOSTIC_EXCELS"
capture mkdir "`gdrive_path'"
capture export delimited using "`gdrive_path'/validation_cadas_vs_1066.csv", replace

display "Validation complete. Results saved to:"
display "  - $data_path/1066_diagnostics/validation_cadas_vs_1066.csv"
display "  - Google Drive: 1066_DIAGNOSTIC_EXCELS/"

*-------------------------------------------------------------------------------
* COUNTRY-SPECIFIC COMPARISON (apples-to-apples)
*-------------------------------------------------------------------------------

display _newline(1)
display "================================================================================"
display "COUNTRY-SPECIFIC COMPARISON: `country_name'"
display "================================================================================"

* Load reference file (has computed variables) and merge in countryid from raw baseline
display "Calculating 1066 Baseline statistics for `country_name' only (countryid=`baseline_countryid')..."

tempfile baseline_country_stats
postfile baseline_country_handle str32 variable double(baseline_n baseline_mean baseline_sd baseline_min baseline_max) using `baseline_country_stats', replace

* Load reference file (has computed variables with matching names)
use "`baseline_path'", clear

* Reference file doesn't have countryid - merge it from raw baseline using pid
capture confirm variable countryid
if _rc != 0 {
    display "  Reference file missing countryid - merging from raw baseline..."
    tempfile ref_data
    save `ref_data'

    * Load raw baseline just to get countryid mapping
    use pid countryid using "`baseline_raw_path'", clear
    tempfile countryid_map
    save `countryid_map'

    * Reload reference and merge in countryid
    use `ref_data', clear
    merge 1:1 pid using `countryid_map', keep(match master) nogenerate
    display "  Merged countryid from raw baseline"
}

* Now filter by countryid
capture confirm variable countryid
if _rc == 0 {
    keep if countryid == `baseline_countryid'
    display "  Filtered to countryid = `baseline_countryid' (`country_name')"
}
else {
    display "  WARNING: Could not filter by country - using full reference dataset"
}

local baseline_country_n = _N
display "  Found `baseline_country_n' cases in 1066 reference for `country_name'"

* Apply same quality filter as CADAS: drop relscore if >50% informant items missing
capture confirm variable MISSTOT
if _rc == 0 {
    replace relscore = . if MISSTOT > 11
    display "  Applied misstot filter: set relscore=. where MISSTOT > 11"
}
else {
    capture confirm variable misstot
    if _rc == 0 {
        replace relscore = . if misstot > 11
        display "  Applied misstot filter: set relscore=. where misstot > 11"
    }
    else {
        display "  Note: misstot not found, quality filter not applied"
    }
}

foreach var of local all_vars {
    capture confirm variable `var'
    if _rc == 0 {
        quietly summarize `var'
        post baseline_country_handle ("`var'") (r(N)) (r(mean)) (r(sd)) (r(min)) (r(max))
    }
    else {
        post baseline_country_handle ("`var'") (.) (.) (.) (.) (.)
    }
}
postclose baseline_country_handle

* Merge with CADAS stats and calculate differences
use `cadas_stats', clear
merge 1:1 variable using `baseline_country_stats', nogenerate

gen double mean_diff = cadas_mean - baseline_mean
gen double mean_pct_diff = ((cadas_mean - baseline_mean) / baseline_mean) * 100 if baseline_mean != 0 & !missing(baseline_mean)

gen byte flag_mean = 0
replace flag_mean = 1 if abs(mean_pct_diff) > 10 & !missing(mean_pct_diff)
replace flag_mean = 1 if abs(mean_diff) > 0.5 & missing(mean_pct_diff) & !missing(mean_diff)

* Sort by absolute pct diff, largest first (before converting to string)
gen abs_pct_diff = abs(mean_pct_diff)
gsort -abs_pct_diff variable
drop abs_pct_diff

* Convert to string with formatting for clean CSV export
foreach var in cadas_mean cadas_sd cadas_min cadas_max baseline_mean baseline_sd baseline_min baseline_max mean_diff {
    tostring `var', replace format(%9.2f) force
}
tostring mean_pct_diff, replace format(%9.0f) force

order variable cadas_n cadas_mean cadas_sd cadas_min cadas_max ///
      baseline_n baseline_mean baseline_sd baseline_min baseline_max ///
      mean_diff mean_pct_diff flag_mean

* Display flagged variables
quietly count if flag_mean == 1
local n_flagged = r(N)
if `n_flagged' > 0 {
    display as result "Variables with large mean differences vs `country_name' baseline:"
    list variable cadas_mean baseline_mean mean_diff mean_pct_diff if flag_mean == 1, noobs
}

* Export country-specific CSV
local country_file = lower("`country_name'")
local country_file = subinstr("`country_file'", " ", "_", .)
export delimited using "$data_path/1066_diagnostics/validation_cadas_vs_1066_`country_file'.csv", replace
capture export delimited using "`gdrive_path'/validation_cadas_vs_1066_`country_file'.csv", replace
display "Country-specific validation saved to: 1066_diagnostics/validation_cadas_vs_1066_`country_file'.csv"

*-------------------------------------------------------------------------------
* PLOT RELSCORE DISTRIBUTION COMPARISON
*-------------------------------------------------------------------------------

display _newline(1)
capture mkdir "$data_path/plots"
local gdrive_plots "/Users/chrissoria/Google Drive/other computers/My Laptop (1)/documents/cadas/data/CADAS data upload/cuba/latest_data/plots"
capture mkdir "`gdrive_plots'"
display "Creating relscore distribution comparison plot..."

* Load CADAS data and keep relscore
use 1066.dta, clear
keep relscore
gen source = 1
label define source_lbl 1 "CADAS `country_name'" 2 "1066 `country_name'"
label values source source_lbl
tempfile cadas_relscore
save `cadas_relscore'

* Load 1066 raw baseline data for this country
use "`baseline_raw_path'", clear
keep if countryid == `baseline_countryid'
display "  Loaded " _N " cases"

* Check what misstot variable exists and apply filter
capture confirm variable MISSTOT
if _rc == 0 {
    replace relscore = . if MISSTOT > 11
    display "  Applied filter using MISSTOT"
}
else {
    capture confirm variable misstot
    if _rc == 0 {
        replace relscore = . if misstot > 11
        display "  Applied filter using misstot"
    }
    else {
        display "  WARNING: No misstot variable found, filter not applied"
    }
}

display "  After filter:"
sum relscore
* Count extreme cases
count if relscore >= 25 & !missing(relscore)
display "  Cases with relscore >= 25: " r(N)
count if relscore == 30
display "  Cases with relscore = 30: " r(N)

* Top-code relscore to 20 to match CADAS max
replace relscore = 20 if relscore > 20 & !missing(relscore)
display "  After top-coding to 20:"
sum relscore
keep relscore
gen source = 2
label values source source_lbl

* Append CADAS data
append using `cadas_relscore'

* Calculate stats for note
quietly sum relscore if source == 1
local cadas_mean = round(r(mean), 0.01)
local cadas_sd = round(r(sd), 0.01)
quietly sum relscore if source == 2
local baseline_mean = round(r(mean), 0.01)
local baseline_sd = round(r(sd), 0.01)

* Create overlaid density plot
twoway (kdensity relscore if source == 1, lcolor(blue) lwidth(medium)) ///
       (kdensity relscore if source == 2, lcolor(red) lwidth(medium)), ///
       legend(order(1 "CADAS `country_name'" 2 "1066 `country_name'") position(1) ring(0)) ///
       xtitle("Relscore") ytitle("Density") ///
       title("Relscore Distribution: CADAS vs 1066 `country_name'") ///
       note("CADAS: mean=`cadas_mean', SD=`cadas_sd' | 1066: mean=`baseline_mean', SD=`baseline_sd'")

graph export "$data_path/plots/relscore_distribution_`country_file'.png", replace width(1200)
capture graph export "`gdrive_plots'/relscore_distribution_`country_file'.png", replace width(1200)
display "Relscore distribution plot saved to: plots/ and Google Drive"

*-------------------------------------------------------------------------------
* PLOT COGSCORE DISTRIBUTION COMPARISON
*-------------------------------------------------------------------------------

display _newline(1)
display "Creating cogscore distribution comparison plot..."

* Load CADAS data and keep cogscore
use 1066.dta, clear
keep cogscore
gen source = 1
label define source_lbl2 1 "CADAS `country_name'" 2 "1066 `country_name'"
label values source source_lbl2
tempfile cadas_cogscore
save `cadas_cogscore'

* Load 1066 raw baseline data for this country
use "`baseline_raw_path'", clear
keep if countryid == `baseline_countryid'
display "  Loaded " _N " cases from 1066 baseline"

keep cogscore
gen source = 2
label values source source_lbl2

* Append CADAS data
append using `cadas_cogscore'

* Calculate stats for note
quietly sum cogscore if source == 1
local cadas_mean = round(r(mean), 0.01)
local cadas_sd = round(r(sd), 0.01)
quietly sum cogscore if source == 2
local baseline_mean = round(r(mean), 0.01)
local baseline_sd = round(r(sd), 0.01)

* Create overlaid density plot
twoway (kdensity cogscore if source == 1, lcolor(blue) lwidth(medium)) ///
       (kdensity cogscore if source == 2, lcolor(red) lwidth(medium)), ///
       legend(order(1 "CADAS `country_name'" 2 "1066 `country_name'") position(11) ring(0)) ///
       xtitle("Cogscore") ytitle("Density") ///
       title("Cogscore Distribution: CADAS vs 1066 `country_name'") ///
       note("CADAS: mean=`cadas_mean', SD=`cadas_sd' | 1066: mean=`baseline_mean', SD=`baseline_sd'")

graph export "$data_path/plots/cogscore_distribution_`country_file'.png", replace width(1200)
capture graph export "`gdrive_plots'/cogscore_distribution_`country_file'.png", replace width(1200)
display "Cogscore distribution plot saved to: plots/ and Google Drive"

*-------------------------------------------------------------------------------
* PLOT RECALL DISTRIBUTION COMPARISON
*-------------------------------------------------------------------------------

display _newline(1)
display "Creating recall distribution comparison plot..."

* Load CADAS data and keep recall
use 1066.dta, clear
keep recall
gen source = 1
label define source_lbl4 1 "CADAS `country_name'" 2 "1066 `country_name'"
label values source source_lbl4
tempfile cadas_recall
save `cadas_recall'

* Load 1066 raw baseline data for this country
use "`baseline_raw_path'", clear
keep if countryid == `baseline_countryid'
display "  Loaded " _N " cases from 1066 baseline"

keep recall
gen source = 2
label values source source_lbl4

* Append CADAS data
append using `cadas_recall'

* Calculate stats for note
quietly sum recall if source == 1
local cadas_mean = round(r(mean), 0.01)
local cadas_sd = round(r(sd), 0.01)
quietly sum recall if source == 2
local baseline_mean = round(r(mean), 0.01)
local baseline_sd = round(r(sd), 0.01)

* Create overlaid density plot
twoway (kdensity recall if source == 1, lcolor(blue) lwidth(medium)) ///
       (kdensity recall if source == 2, lcolor(red) lwidth(medium)), ///
       legend(order(1 "CADAS `country_name'" 2 "1066 `country_name'") position(1) ring(0)) ///
       xtitle("Recall (10-word delayed)") ytitle("Density") ///
       title("Recall Distribution: CADAS vs 1066 `country_name'") ///
       note("CADAS: mean=`cadas_mean', SD=`cadas_sd' | 1066: mean=`baseline_mean', SD=`baseline_sd'")

graph export "$data_path/plots/recall_distribution_`country_file'.png", replace width(1200)
capture graph export "`gdrive_plots'/recall_distribution_`country_file'.png", replace width(1200)
display "Recall distribution plot saved to: plots/ and Google Drive"

*-------------------------------------------------------------------------------
* PLOT AGE DISTRIBUTION COMPARISON
*-------------------------------------------------------------------------------

display _newline(1)
display "Creating age distribution comparison plot..."

* Load CADAS socio data for age
use "$data_path/socio.dta", clear
rename s_2_3 age
replace age = . if age > 120  // Filter out 888/999 missing codes
keep age
gen source = 1
label define source_lbl3 1 "CADAS `country_name'" 2 "1066 `country_name'"
label values source source_lbl3
tempfile cadas_age
save `cadas_age'

* Load 1066 raw baseline data for this country
use "`baseline_raw_path'", clear
keep if countryid == `baseline_countryid'
display "  Loaded " _N " cases from 1066 baseline"

keep age
gen source = 2
label values source source_lbl3

* Append CADAS data
append using `cadas_age'

* Calculate stats for note
quietly sum age if source == 1
local cadas_mean = round(r(mean), 0.01)
local cadas_sd = round(r(sd), 0.01)
quietly sum age if source == 2
local baseline_mean = round(r(mean), 0.01)
local baseline_sd = round(r(sd), 0.01)

* Create overlaid density plot
twoway (kdensity age if source == 1, lcolor(blue) lwidth(medium)) ///
       (kdensity age if source == 2, lcolor(red) lwidth(medium)), ///
       legend(order(1 "CADAS `country_name'" 2 "1066 `country_name'") position(1) ring(0)) ///
       xtitle("Age") ytitle("Density") ///
       title("Age Distribution: CADAS vs 1066 `country_name'") ///
       note("CADAS: mean=`cadas_mean', SD=`cadas_sd' | 1066: mean=`baseline_mean', SD=`baseline_sd'")

graph export "$data_path/plots/age_distribution_`country_file'.png", replace width(1200)
capture graph export "`gdrive_plots'/age_distribution_`country_file'.png", replace width(1200)
display "Age distribution plot saved to: plots/ and Google Drive"
display "--------------------------------------------------------------------------------"

*-------------------------------------------------------------------------------
* PLOT EDUCATION COMPARISON
*-------------------------------------------------------------------------------

display _newline(1)
display "Creating education comparison..."

* Load CADAS socio data for education (years)
use "$data_path/socio.dta", clear
rename s_2_8c educ_years
replace educ_years = . if educ_years > 25  // Filter out invalid/missing codes (88, 99, etc.)
display "  CADAS education (years) distribution:"
tab educ_years
sum educ_years
gen primary_plus = (educ_years >= 6) if !missing(educ_years)
display "  CADAS: completed primary (6+ years) or more"
tab primary_plus
keep primary_plus
gen source = 1
tempfile cadas_educ
save `cadas_educ'

* Load 1066 raw baseline data for this country
use "`baseline_raw_path'", clear
keep if countryid == `baseline_countryid'
display "  Loaded " _N " cases from 1066 baseline"

* Use PEDUC (categorical: 1=none, 2=some/incomplete primary, 3=completed primary, 4=secondary, 5=tertiary)
* Primary or more = PEDUC >= 3
gen primary_plus = (PEDUC >= 3) if !missing(PEDUC)
display "  1066 education: completed primary or more"
tab primary_plus

keep primary_plus
gen source = 2

* Append CADAS data
append using `cadas_educ'

* Calculate percentages
quietly sum primary_plus if source == 1
local cadas_pct : display %4.1f r(mean) * 100
quietly sum primary_plus if source == 2
local baseline_pct : display %4.1f r(mean) * 100

display "  CADAS: `cadas_pct'% with primary education or more"
display "  1066:  `baseline_pct'% with primary education or more"

* Create bar chart
graph bar (mean) primary_plus, over(source, relabel(1 "CADAS `country_name'" 2 "1066 `country_name'")) ///
    ytitle("Proportion with Primary Education+") ///
    title("Education: CADAS vs 1066 `country_name'") ///
    note("CADAS: `cadas_pct'% | 1066: `baseline_pct'%") ///
    ylabel(0(0.2)1) blabel(bar, format(%4.2f))

graph export "$data_path/plots/education_comparison_`country_file'.png", replace width(1200)
capture graph export "`gdrive_plots'/education_comparison_`country_file'.png", replace width(1200)
display "Education comparison plot saved to: plots/ and Google Drive"
display "--------------------------------------------------------------------------------"

* Reload 1066.dta for subsequent summary in master file
use 1066.dta, clear
